# Dev profile configuration
# Disable Hibernate schema handling so we can rely on seed SQL only
spring.jpa.hibernate.ddl-auto=none

# Turn off open-in-view warning in console
spring.jpa.open-in-view=false

# Enable sqlserver specific behaviors
spring.datasource.xa-properties.dataSourceClassName=com.microsoft.sqlserver.jdbc.SQLServerXADataSource

